[project]
name = "pdf-chef"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "reportlab>=4.4.3",
]

[dependency-groups]
dev = [
    "ruff>=0.13.0",
]
