io:
  output_file_name: ../pdfs/recipes.pdf
  input_recipe_file_path: ../recipes/pompoen_risotto.json

document_margins:
  left: 20  # Unit: pixels
  right: 20  # Unit: pixels

section_margins:
  top: 10  # Unit: pixels
  bottom: 10  # Unit: pixels

layout_cover:
  image_height: 150  # Unit: pixels

font:
  font_name: Helvetica
  font_size: 16
  font_shift_factor: 1.8

colors:
  color_mode: "repeating"  # Allowed values: ["repeating"]
  palette:
    - [0.87, 0.85, 0.55]  # Normalized RGB
    - [0.87, 0.72, 0.53]
